# Generated by Django 4.2.1 on 2023-06-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='tdate',
        ),
    ]
